### ISSUE TITLE
Error when running the first time

### ISSUE THREAD

**Issue by npentell** [terrelsa13/media_cleaner#102]
Hi, im running the script for the first time and getting the following error. Any advice?

`Start...
Cleaning media for server at: http://localhost:8097/emby
----------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------
Get List Of Media For:
nick - HIDDEN
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/MUMC/mumc.py", line 105, in <module>
    MUMC()
  File "/opt/MUMC/mumc.py", line 76, in MUMC
    cfg=init_getMedia(cfg)
  File "/opt/MUMC/mumc_modules/mumc_get_media.py", line 819, in init_getMedia
    episode_returns=get_mediaItems(the_dict,the_dict['episode_dict']['media_type'],user_info,episode_returns)
  File "/opt/MUMC/mumc_modules/mumc_get_media.py", line 580, in get_mediaItems
    var_dict['item_isWhitelisted']=get_isItemWhitelisted_Blacklisted('whitelist',item,user_info,the_dict)
  File "/opt/MUMC/mumc_modules/mumc_blacklist_whitelist.py", line 42, in get_isItemWhitelisted_Blacklisted
    item_isWhitelisted_isBlacklisted, itemWhitelistedBlacklistedValue=get_isItemMatching_doesItemStartWith(ItemPath,user_wlbllib_path_json,the_dict)
  File "/opt/MUMC/mumc_modules/mumc_compare_items.py", line 60, in get_isItemMatching_doesItemStartWith
    item_two = item_two.replace('\\','/')
AttributeError: 'list' object has no attribute 'replace'`

**Comment by terrelsa13** [comment]
Take a look at [v5.4.2](https://github.com/terrelsa13/MUMC/releases/tag/v5.4.2) on the [MUMC_Latest](https://github.com/terrelsa13/MUMC) branch.

Let me know if you have any more issues.

**Comment by npentell** [comment]
I'm on my phone now so I will have to confirm but I just installed it
tonight and I believe that's the version I am on

**Comment by terrelsa13** [comment]
The script will print information to the console when it starts running. Version is part of the information and be be used to confirm the version (v5.4.2) just released about 10mins ago is the version being used.

**Comment by npentell** [comment]
Oh if it was just released then I do not have it. I will give it a try.

Thank you!

**Comment by terrelsa13** [comment]
Np. Let me know if this does or does not fix the issue.

**Comment by npentell** [comment]
The update fixed it. Works like a charm.  Thank you!

**Comment by terrelsa13** [comment]
You are welcome! I will close this issue.
