### ISSUE TITLE
Unable to get information from server during processing of: get_all_library_subfolders

### ISSUE THREAD

**Issue by c1illsl** [terrelsa13/media_cleaner#104]
HTTPError: Unable to get information from server during processing of: get_all_library_subfolders
  Object: <bound method Request.header_items of <urllib.request.Request object at 0x7f7a015319a0>>
     URL: http://localhost:8096/Library/SelectableMediaFolders
  Method:
  Header: {'Authorization': 'MediaBrowser Client="mumc.py", Device="Multi-User Media Cleaner", DeviceId="MUMC", Version="5.6.4", Token="7364ed3b50cb4e0987842a85171d520f"', 'Content-type': 'application/json'}
    Data: None

HTTPError: 404 - Not Found

Check password and/or remove any GUI API keys for MUMC

**Comment by terrelsa13** [comment]
Apologies, this is my fault. I recently updated the user and library builders. It works with Emby. I never had the time to go back and verify it works with Jellyfin. I will take a look at this during my "free times" in the coming week.

#### I can only offer two immediate solutions. Neither are perfect:
1. Use an older version of MUMC.
   1. [MUMC v5.4.2](https://github.com/terrelsa13/MUMC/releases/tag/v5.4.2) was the last version before the user and library builders were updated
2. Install Emby.
   1. I know. Like I said, neither are perfect.

I will let you know once I have a solution for Jellyfin.

Again, my apologies.

**Comment by terrelsa13** [comment]
@c1illsl That was easier than I thought it was going to be.

Try the latest release [v5.6.5](https://github.com/terrelsa13/MUMC/releases). Let me know if there are any more issues.

**Comment by c1illsl** [comment]
All fixed thank you so much !

Clay
