### ISSUE TITLE
Feature Request: Keep minimum

### ISSUE THREAD

**Issue by SenorSmartyPants** [terrelsa13/media_cleaner#15]
Option to keep a minimum of watched episodes (this would really only apply to TV media I think). If all episodes of a show are deleted, then a new episode is acquired, the show will not appear in "Next Up". Keeping at least 1 episode will allow the new episode to display in "Next Up"

This could also be tag based, so some shows would be completely removed. Or it could be based on continuing/ended status. Keep at least 1 for continuing shows.

**Comment by terrelsa13** [comment]
@SenorSmartyPants 
I have been taking a look at this one. I only have x4 series that have the `Status` field. Do you have a better hit rate? Or am I barking up the wrong tree with this query?

http://watch.tv/emby/Items?Recursive=true&Fields=Status,SeriesStatus&IncludeItemTypes=Series&api_key=abcdef5297e44vwxyz4de93f42598765

I like tagging allows more flexibility for each series. BUT I also do not like that tagging requires manually editing the metadata for the series in emby/jellyfin to add the tag.

Suggestions?

**Comment by listy-bit** [comment]
Continuing/ended status is irrelevant unless you have just watched the final released episode of  a season or series. The widest utility would be to simply ask the user how many watched episodes of a series should be kept, and they'll have to manually delete season/series finales as there's no reliable flag to tell if it really is the last episode of a series. Or if they want to delete a season finale or keep it for next season.

**Comment by terrelsa13** [comment]
@listy-bit 
You are right about the continuing/ending status. I was thinking it worked at the season level. But it makes more sense that it works at the series level.

Although it would be nice if the continuing/ending status was more consistent (at least it is not for me). It could have been used as the indicator to delete any of the remaining episodes once a series ends.
