### ISSUE TITLE
mumc does not evaluate tvshows

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#32]
Script Verion: 2.1.7  &&  Script Verion: 3.0.14-beta

Both do not list keeping/deleting of tvshows almost same configuration of v1 does list keeping/delete of tvshows. Scripts are working on the same set and same emby server

Using blacklist on 2 library's. Expecting to see a listing of played episodes which are played <14days ago as specified in config.

Attached is 2.1.7 config script

[media_cleaner_config.py.txt](https://github.com/terrelsa13/MUMC/files/9226939/media_cleaner_config.py.txt)

**Comment by terrelsa13** [comment]
Hey @keppo070 

>Both do not list keeping/deleting of tvshows almost same configuration of v1 does list keeping/delete of tvshows. Scripts are working on the same set and same emby server

Assuming v2... I copied your config and ran it on my server. It works as expected. Episodes played <14 days ago are shown with [Keeping]. Episodes played >=14 days ago are shown with [Delete].

>Using blacklist on 2 library's. Expecting to see a listing of played episodes which are played <14days ago as specified in config.

Assuming v2... I am not fully understanding what you are looking for. The below config options will query the server for all played movies and episodes. The movies and episodes the server returns are then inspected to see which are played >=14 days ago. Any played >=14 days ago are added to the delete list. Any episodes/movies played <14 days ago are not added to the delete list.
```
played_age_movie=14
played_age_episode=14
played_age_audio=-1
```
>Attached is 2.1.7 config script

Are you able to send your v3 config so I can if I am able to find the issue there?

**Comment by keppo070** [comment]
there must be something wrong with my setup

I am still using v1 and I was expecting the same results from v2 & v3. All are run on the same library's.  V2 & v3 are the same results. But both dont seem to show any episodes (keeping or deleting. Which is odd for a tv-addict.

Inspecting the results from v1 seems also to have same oddities but still more realistic that no episodes for v2 & v3

attached the result list van v1 and v2 and result & config for v3

[media_cleaner_result_v1.txt](https://github.com/terrelsa13/MUMC/files/9228350/media_cleaner_result_v1.txt)
[media_cleaner_result_v2.txt](https://github.com/terrelsa13/MUMC/files/9228512/media_cleaner_result_v2.txt)

[mumc_config.py.txt](https://github.com/terrelsa13/MUMC/files/9228513/mumc_config.py.txt)
[media_cleaner_result_v3.txt](https://github.com/terrelsa13/MUMC/files/9228525/media_cleaner_result_v3.txt)

**Comment by terrelsa13** [comment]
Ahh... v1 is VERY different compared to v2 and v3 with how data is collected for each user. v1 was more of a wrecking ball. I don't have a readily available copy of v1 anymore so I can't look right now to remember how things were done. But I see the `Summary Of Deleted Media:` for all x3 versions is the same. So things appear to be working on your end as expected for all versions.

FYI - The media_cleaner_results_v#.txt links above are the normal output, but they are not the `DEBUG` output. With `DEBUG=True` in the config file, there will be very detailed information about every media item inspected along with data the script creates.

To make this process easier for you, please do not edit any of the outputs by **x**-ing out things. Unless the IP address the script is using to access the server is a public IP address, there is no reason to **x** it out. Nor is there a need to **x** out the user names, user keys, or auth keys. Doing so slows down the debugging process.

I suggest using v3 as v1 is no longer support and v2 will no longer be supported at the beginning of August.

**Comment by keppo070** [comment]
I included all the results because there are created on the same libraries and files. In v1 there are tvshows but they dont appear in v2 and v3... there are only movies. I would expect to see some tvshows as I watch tvshows every day

Do you have an anonimiser script for the debug file?

**Comment by keppo070** [comment]
Script Verion: 3.1.0 

i did some testing with various options. The script works for episodes OR movies.  I changed my config to ONLY work with episodes than I see its evaluating episodes. When I add the movie library to the config I can only see movies.

The debuglog does not contain episodes

Singleuser or Multpleusers does not influence my output.

**Comment by keppo070** [comment]
I did some more testing. I installed Jellyfin. configured mumc and did a test. Now I only get episodes and not movies. Examing the log. It seems to use only the first LibraryID.

EMBY
```
-----------------------------------------------------------
Script Verion: 3.1.0
-----------------------------------------------------------
Start...
Cleaning media for server at: http://192.168.178.11:8096/emby
-----------------------------------------------------------

Building library for user with Id: 62890d97fefb45178d112384702c4cd4
Building library for user with name: Anne
Library Id: f137a2dd21bbc1b99aa5c0f6bf02a805
Collection Type: movies
Path: /data/movies
Network Path:
Library Id: 6c2a057148b4d7c20a207c789aba6d07
Collection Type: tvshows
Path: /data/tvshows
Network Path:
Building library for user with Id: 62890d97fefb45178d112384702c4cd4
Building library for user with name: Anne
http://192.168.178.11:8096/emby/Users/62890d97fefb45178d112384702c4cd4/?api_key=f879xxxxfb47
current_user - url request
http://192.168.178.11:8096/emby/Users/62890d97fefb45178d112384702c4cd4/?api_key=f879xxxxfb47
current_user - data
```

JELLYFIN
```
-----------------------------------------------------------
Script Verion: 3.1.0
-----------------------------------------------------------
Start...
Cleaning media for server at: http://192.168.178.11:8097
-----------------------------------------------------------

Building library for user with Id: 25c9ad11672f4489bfc06e6f0d5d6329
Building library for user with name: adm.pat
Library Id: 5ddaa59a73205234890fdcfc683e14ed
Collection Type: tvshows
Path: /data/tvshows
Network Path:
Library Id: db4c1708cbb5dd1676284a40f2950aba
Collection Type: movies
Path: /data/movies
Network Path:
Building library for user with Id: 25c9ad11672f4489bfc06e6f0d5d6329
Building library for user with name: adm.pat
http://192.168.178.11:8097/Users/25c9ad11672f4489bfc06e6f0d5d6329/?api_key=c079xxxx626e
current_user - url request
http://192.168.178.11:8097/Users/25c9ad11672f4489bfc06e6f0d5d6329/?api_key=c079xxxx626e
current_user - data
```

**Comment by keppo070** [comment]
Created a fresh installation emby. 
added some media
marked some media as read 
created a full debug log

[mumc.log](https://github.com/terrelsa13/MUMC/files/9235224/mumc.log)
[mumc_config.py.log](https://github.com/terrelsa13/MUMC/files/9235247/mumc_config.py.log)

**Comment by terrelsa13** [comment]
I will look into this one a little bit deeper tomorrow.

I plan to make you urls that will probe your servers API so we can figure out why only movies or episodes work, but not both. Are you able to point me to the config file that is the closest to how you want the final setup to behave? This will help me make sure I use the right user_ids, lib_ids, and user_keys in these manual urls.

**Comment by keppo070** [comment]
I created a new log and config with the latest beta on my test emby installation

[mumc.311b.log](https://github.com/terrelsa13/MUMC/files/9243635/mumc.311b.log)

[mumc_config.py.txt](https://github.com/terrelsa13/MUMC/files/9243639/mumc_config.py.txt)

**Comment by keppo070** [comment]
I did some testing with v2.1.8 and its got something to do with the order of de library's. If I switch the order it works or doesn't work

I have added 2 logfiles and 2 corresponding config files. The only difference is the order of ```user_bl_libs```

[media_cleaner_config.py.01.txt](https://github.com/terrelsa13/MUMC/files/9253263/media_cleaner_config.py.01.txt)
[01.log](https://github.com/terrelsa13/MUMC/files/9253264/01.log)

[media_cleaner_config.py.10.txt](https://github.com/terrelsa13/MUMC/files/9253266/media_cleaner_config.py.10.txt)
[10.log](https://github.com/terrelsa13/MUMC/files/9253268/10.log)

01 --> does NOT work
10 --> does work

**Comment by keppo070** [comment]
I like to add the same issue is with 311-beta. Only the first library in ```user_bl_libs``` is evaluated

[mumc_config.py.txt](https://github.com/terrelsa13/MUMC/files/9254242/mumc_config.py.txt)
[mumc311-beta.log](https://github.com/terrelsa13/MUMC/files/9254243/mumc311-beta.log)

Hope this helps in tracking the issue.

**Comment by terrelsa13** [comment]
## Instructions

* Copy/Paste these API queries into an internet browser that can access your Emby Server webpage (`http://192.168.178.14:8097/emby/`).
* Server should return data after each API query.
* At the top select "Save".
* Name and save file.
* Post a link for each file.


## Movie Queries

Tries to return x10 played movies.
```
http://192.168.178.14:8097/emby/Users/9681474d4c994c3cb511715fa7fa41dc/Items?ParentID=f137a2dd21bbc1b99aa5c0f6bf02a805&IncludeItemTypes=Movie&StartIndex=0&Limit=10&IsPlayed=True&Recursive=True&EnableImages=False&CollapseBoxSetItems=False&EnableUserData=True&api_key=c484bbd032f541c892896da0400cc16f
```
Tries to return x10 unplayed movies.
```
http://192.168.178.14:8097/emby/Users/9681474d4c994c3cb511715fa7fa41dc/Items?ParentID=f137a2dd21bbc1b99aa5c0f6bf02a805&IncludeItemTypes=Movie&StartIndex=0&Limit=10&IsPlayed=False&Recursive=True&EnableImages=False&CollapseBoxSetItems=False&EnableUserData=True&api_key=c484bbd032f541c892896da0400cc16f
```
Tries to return x25 movies. The could be played or unplayed.
```
http://192.168.178.14:8097/emby/Users/9681474d4c994c3cb511715fa7fa41dc/Items?ParentID=f137a2dd21bbc1b99aa5c0f6bf02a805&IncludeItemTypes=Movie&StartIndex=0&Limit=25&Recursive=True&EnableImages=False&CollapseBoxSetItems=False&EnableUserData=True&api_key=c484bbd032f541c892896da0400cc16f
```

## Episode Queries

Tries to return x10 played episodes.
```
http://192.168.178.14:8097/emby/Users/9681474d4c994c3cb511715fa7fa41dc/Items?ParentID=6c2a057148b4d7c20a207c789aba6d07&IncludeItemTypes=Episode&StartIndex=0&Limit=100&IsPlayed=True&Recursive=True&EnableImages=False&CollapseBoxSetItems=False&EnableUserData=True&api_key=c484bbd032f541c892896da0400cc16f
```
Tries to return x10 unplayed episodes.
```
http://192.168.178.14:8097/emby/Users/9681474d4c994c3cb511715fa7fa41dc/Items?ParentID=6c2a057148b4d7c20a207c789aba6d07&IncludeItemTypes=Episode&StartIndex=0&Limit=100&IsPlayed=False&Recursive=True&EnableImages=False&CollapseBoxSetItems=False&EnableUserData=True&api_key=c484bbd032f541c892896da0400cc16f
```
Tries to return x25 episodes. The could be played or unplayed.
```
http://192.168.178.14:8097/emby/Users/9681474d4c994c3cb511715fa7fa41dc/Items?ParentID=6c2a057148b4d7c20a207c789aba6d07&IncludeItemTypes=Episode&StartIndex=0&Limit=100&Recursive=True&EnableImages=False&CollapseBoxSetItems=False&EnableUserData=True&api_key=c484bbd032f541c892896da0400cc16f
```

## Question
I noticed your movie libraryId is EXACTLY the same as my movie libraryId. I searched the script and I have not accidentally hard-coded my movie libraryId into it.

* Have you manually modified any of the libraryIds?
  - If yes, please change the API queries above so they are using the correct Ids.

**Comment by keppo070** [comment]
[queries.zip](https://github.com/terrelsa13/MUMC/files/9258708/queries.zip)

### Answer
I have not modified any IDs. Do not know how. This is a fresh install and new created library from within the gui. I use a docker image from linuxserver maybe that could be it

**Comment by terrelsa13** [comment]
Will you confirm you only have x3 movies in your movie library?
`Movies25xplayedunplayed.json` only returned x3 items.

Of the x3 movies only x1 is showing as played. It was last played 2022-August-01st. Which is less than 14days ago.
Does this sound right?

Of the x8842 episodes only x3 are played. x1 was played 2022-August-01st the other x2 were played 2022-August-02nd.
Does this sound right?

**Comment by keppo070** [comment]
This is my test installation

Which contains
* 3 movies in total
* 2 users
* each user has 1 different movie played  (dont know how to verify played date in the gui) but it is played less than 14d ago

* **23 epsisodes** and 1 user (patrick) has 3 played episode  the other user 1 played episode
* ![Ovu5M60hor](https://user-images.githubusercontent.com/8713528/183033212-12f1bcf8-4622-4181-a3dc-ac7943ef2229.png)


The episodes is not correct by looking in the gui

**Comment by terrelsa13** [comment]
The played episodes in `episode10xplayed.json` match what the GUI is showing.

If you open `Movies10xplayed.json` in a internet browser it will show if the played movie also matches.

The TV and Movie libraries are both accessible on your test server. Try lowering the movie/episode played and created days on the test server to 1. Double check `REMOVE_FILES=False`. And run it again. Does this process both the TV and Movie libraries?

I have been needing to update this script for a while now to make it easier to collect and send the DEBUG data. This issue is giving me the push I need to make those changes. In the next 24hrs I will push an update to v3 (v3.1.2-beta). The update will improve the debug information and save it to `/the/script/directory/mumc_DEBUG.log`.

I will let you know once this updated is available.

**Comment by terrelsa13** [comment]
**v3.1.2-beta is available.**

The v3.1.1-beta configuration should work. But if you want to be on the safe side, I recommend letting it rebuild your configuration file. 

Follow the instructions above and upload the mumc_DEBUG.log file.

**Comment by keppo070** [comment]
> The TV and Movie libraries are both accessible on your test server. Try lowering the movie/episode played and created days on the test server to 1. Double check `REMOVE_FILES=False`. And run it again. Does this process both the TV and Movie libraries?

Do you want me to test this with v2? But setting the value to 1 would just affect the summary. The listing per user/library would not change



> Of the x8842 episodes only x3 are played. x1 was played 2022-August-01st the other x2 were played 2022-August-02nd.
> Does this sound right?

Where is this number of x8842 episodes coming from.

Here the results of mumc312-beta. Almost there. User patrick still no movies visible
[mumc_config.py.txt](https://github.com/terrelsa13/MUMC/files/9282918/mumc_config.py.txt)
[mumc_DEBUG.log](https://github.com/terrelsa13/MUMC/files/9282921/mumc_DEBUG.log)

**Comment by terrelsa13** [comment]
>Where is this number of x8842 episodes coming from.

Open `episodes25xplayedunplayed.json` in an internet browser. Select the "Collapse All" button. You will then be able to see the total record count.

>Here the results of mumc312-beta. Almost there. User patrick still no movies visible

The log file works. I am able to see what is happening now. It appears there may be an issue with the nested loop for the libraries.

The outer loop should loop thru each user. The inner loop should loop thru each library.
I can see it starts with `username: Anne` and sends queries for the movie library. It then moves on to `username: Patrick`. Along with the next library which is the episode library.

`username: Anne` has their episode library skipped.
`username: Patrick` has their movie library skipped.

I will look into this a little deeper tomorrow.

**Comment by terrelsa13** [comment]
I removed the `networkpath` from each blacklisted library and I was able to reproduce you issue.

I have added fake `networkpath`s to your `user_bl_libs` variable. Delete the current `user_bl_libs` line and Copy/Paste the one below into your config:
```
user_bl_libs='[{"userid": "8b3c3db5bf59403184aa1546cdc66c91", "username": "Anne", "0": {"libid": "f137a2dd21bbc1b99aa5c0f6bf02a805", "collectiontype": "movies", "path": "/data/movies", "networkpath": "smb://data/movies"}, "1": {"libid": "6c2a057148b4d7c20a207c789aba6d07", "collectiontype": "tvshows", "path": "/data/tvshows", "networkpath": "smb://data/tvshows"}}, {"userid": "9681474d4c994c3cb511715fa7fa41dc", "username": "patrick", "1": {"libid": "6c2a057148b4d7c20a207c789aba6d07", "collectiontype": "tvshows", "path": "/data/tvshows", "networkpath": "smb://data/tvshows"}, "0": {"libid": "f137a2dd21bbc1b99aa5c0f6bf02a805", "collectiontype": "movies", "path": "/data/movies", "networkpath": "smb://data/movies"}}]'
```
Let me know if this "fixes" it.

I will look into this more tomorrow.

**Comment by keppo070** [comment]
Yes, this fixes it. Tried it with MUMC-312.
[mumc_config.py.txt](https://github.com/terrelsa13/MUMC/files/9289212/mumc_config.py.txt)
[mumc_DEBUG.log](https://github.com/terrelsa13/MUMC/files/9289217/mumc_DEBUG.log)



I marked an episode in the GUI as played and it is immediately found by MUMC. So this works.

Just curious but my setup is rather straightforward (mostly default, i think) is this something related to my setup?

**Comment by keppo070** [comment]
Just checked in v2. The fix works there also & ```max_age_movie=2``` works

Just checked in v312-b. The ```movie_created_days=2``` option does **not** work

**Comment by terrelsa13** [comment]
>Just checked in v312-b. The movie_created_days=2 option does not work

What are the values for `movie_created_played_count_comparison` and `movie_created_played_count`?

**Comment by keppo070** [comment]
My config file is https://github.com/terrelsa13/MUMC/issues/32#issuecomment-1209184236

``` movie_created_played_count_comparison='>=' ```

``` movie_created_played_count=1 ```

**Comment by terrelsa13** [comment]
This issue should now be fixed in the latest version of both v2 and v3.

Long story short; when one of the library attributes was empty it was causing the inner loop to end early.

**Comment by keppo070** [comment]
Thanx for fixing and to bear with me....

upgrade v2 and v3 on my main library with is still running v1. Leave it running in parallel for now. Saw allready something wierd on the main server. Cant provide log but still like to mention it. Definitely something wierd on my main server

v2
```
:[KEEPING] - Movie - French - France 3 Cinéma - Unplayed - Created 189 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - MovieID: 12345
:*[DELETE] - Movie - French - France 3 Cinéma - Played 188 days ago - Created 189 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - MovieID: 12345
```

v3
```
:[KEEPING] - Movie - French - France 3 Cinéma - Unplayed - Play Count: 0 - Created 189 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - MovieID: 12345
:[KEEPING] - Movie - French - France 3 Cinéma - **Unplayed - Play Count: 1** - Created 189 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - MovieID: 12345

```

**Comment by terrelsa13** [comment]
Np.

This difference you show above is something I noticed and fixed in the early stages of v3.

Each media item returns the following under `UserData:`
* `PlayCount=#`
* `Played=boolean`

For v2 I made the assumption when `PlayCount` > 0 it must mean the media item is watched. I discovered during v3 development this was not a good way to verify if something was watched.

### Example:
* MovieX is just released
  * `PlayCount=0`
  * `Played=False`
* You watch MovieX
  * `PlayCount=1`
  * `Played=True`
* You manually set MovieX to Unwatched in the GUI
  * `PlayCount=1`
  * `Played=False`
* You watch MovieX again
  * `PlayCount=2`
  * `Played=True`

For v2 the script treats the movie as **played**, because `PlayCount` is always > 0 after it is watched. `PlayCount` is not affected by manually setting it to Unwatched in the GUI.
For v3 the script treats the movie as **unplayed**, because `Played=False` and follows the watched/unwatched status shown in the GUI.
