### ISSUE TITLE
[Request] - Add date and time to log file

### ISSUE THREAD

**Issue by GulyFMG** [terrelsa13/media_cleaner#34]
Would it be possible to add the date and time to the log file? Maybe a switch. after a while the logs get pretty big and searching by date is always nice.

TY

**Comment by terrelsa13** [comment]
Hey @GulyFMG,

Need some clarification:
* Are you talking about the output that is printed to the console?
  * i.e. `:*[DELETE]` and `:{KEEPING]`?
* Or are you talking about the mumc_DEBUG.log file
  * Created when `DEBUG=True` in the config file for v3-beta of the script?

**Comment by GulyFMG** [comment]
Hello,

First sorry for the short explanation. I was talking in the output that is printed to the console? Right now i am calling your script and sending the output to a log file via crontab. I think i could do the reverse and create a bash calling your script and then inject the date to the log.

**Comment by terrelsa13** [comment]
This will append the date-time stamp to the filename in crontab:
$ `23 1 * * 1 /usr/local/bin/python3.10 /script/directory/media_cleaner.py > /your/log/FileName$(date +"%Y%m%d%H%M%S").log 2>&1`

The output file will look like this: _FileName.YYYYMMDDHHMMSS.log_

YYYY - Year
MM - Month
DD - Day
HH - Hour
MM - Minute
SS - Second

I will also update the script to output a timestamp underneath the script version print out:
```
-----------------------------------------------------------
Script Verion: 2.x.x
Time Stamp: YYYYMMDDHHMMS
-----------------------------------------------------------
```

**Comment by GulyFMG** [comment]
> $

TY very much for this... i was missing only that little symbol on my side to make it work, i dont code that often so my brain sometimes skips important stuff 👍 

Script Verion: 2.x.x
Time Stamp: YYYYMMDDHHMMS

Something like this would be great.

**Comment by terrelsa13** [comment]
No problem!

Just checked in v2.1.10. It should output the timestamp at the beginning of the console output.
