### ISSUE TITLE
Playcount vs Played in Jellyfin

### ISSUE THREAD

**Issue by SenorSmartyPants** [terrelsa13/media_cleaner#36]
Currently, JF will update playcount every time you play an item, no matter the duration. So if you play an item for 5 seconds and stop, playcount increases. But item would not be marked as played.

Please only delete media if item is considered `Played` and not just based on `playcount`.

**Comment by terrelsa13** [comment]
Yes. You are correct. This is a known shortcoming of v2 that has addressed with v3. I have stopped development on v2. Please update to v3.
