### ISSUE TITLE
getting the played ## days ago the same for all movies

### ISSUE THREAD

**Issue by EdeAbreu23** [terrelsa13/media_cleaner#38]
Hello Terrelsa,

so i am testing your script and tv shows looks to be working correctly but for movies, i get all movies with the same played days ago of 19230 days. not sure why this is happening
![image](https://user-images.githubusercontent.com/7027367/187005055-55ce975f-d5e5-4d45-b423-d289754b83c3.png)

**Comment by terrelsa13** [comment]
Hey @elvis0288 
I am assuming you are using the [latest release](https://github.com/terrelsa13/MUMC/releases). If not, please update to the latest release.

Then...
1. Disable episodes and audio (i.e set to ```-1```)
2. Do not change your movie config options
3. Set ```DEBUG=4```
4. Run the script
5. Attach the ```mumc_DEBUG.log``` here (it will be in the same directory as the ```mumc.py``` script)

**Comment by EdeAbreu23** [comment]
hello @terrelsa13,

here is the logs you asked for

`-----------------------------------------------------------

-----------------------------------------------------------
Script Version: 3.2.2
Time Stamp: 20220828200902

server_brand='jellyfin'
user_keys=[
    "ELyLI:f00a99a47cc64c21a72b0af93dd5082e",
    "Johannasanchez168:7597f526950c4eb5bc6d596c5ef99507",
    "erika:233e518a45954446b0265dd28fef5390",
    "jackeline:52adb8ad6c074931a4a5bca1a22e6df4"
]
movie_played_days=365
episode_played_days=-1
audio_played_days=-1
audiobook_played_days=-1
movie_created_days=-1
episode_created_days=-1
audio_created_days=-1
audiobook_created_days=-1
movie_played_count_comparison='>='
episode_played_count_comparison='>='
audio_played_count_comparison='>='
audiobook_played_count_comparison='>='
movie_created_played_count_comparison='>='
episode_created_played_count_comparison='>='
audio_created_played_count_comparison='>='
audiobook_created_played_count_comparison='>='
movie_played_count=1
episode_played_count=1
audio_played_count=1
audiobook_played_count=1
movie_created_played_count=1
episode_created_played_count=1
audio_created_played_count=1
audiobook_created_played_count=1
multiuser_play_count_movie=0
multiuser_play_count_episode=0
multiuser_play_count_audio=0
multiuser_play_count_audiobook=0
blacktag=''
delete_blacktagged_movie=0
delete_blacktagged_episode=0
delete_blacktagged_audio=0
delete_blacktagged_audiobook=0
whitetag=''
minimum_number_episodes=0
minimum_number_played_episodes=0
minimum_number_episodes_behavior='Min Played Min Unplayed'
REMOVE_FILES='False'
keep_favorites_advanced_movie_genre=0
keep_favorites_advanced_movie_library_genre=0
keep_favorites_advanced_episode_genre=0
keep_favorites_advanced_season_genre=0
keep_favorites_advanced_series_genre=0
keep_favorites_advanced_tv_library_genre=0
keep_favorites_advanced_tv_studio_network=0
keep_favorites_advanced_tv_studio_network_genre=0
keep_favorites_advanced_track_genre=0
keep_favorites_advanced_album_genre=0
keep_favorites_advanced_music_library_genre=0
keep_favorites_advanced_track_artist=0
keep_favorites_advanced_album_artist=0
keep_favorites_advanced_audio_book_track_genre=0
keep_favorites_advanced_audio_book_track_genre=0
keep_favorites_advanced_audio_book_library_genre=0`

Thanks!

**Comment by EdeAbreu23** [comment]
@terrelsa13 ,

after more investigation, looks like it is showing that date when the movies watched status are coming from trakt so nothing to do with your script. thank you for this amazing script

**Comment by EdeAbreu23** [comment]
@terrelsa13,

so i set delete media as true but it is not deleting anything but i am not sure why.
ot shows whitelist true but i select that path as blacklist
![image](https://user-images.githubusercontent.com/7027367/187105863-281207c3-70f1-4dbf-acbd-23fa1def1d98.png)

**Comment by terrelsa13** [comment]
Not sure what happened above. But that is not the complete debug log. It is only showing the beginning of the debug log. But it sounds like this is related to Trakt. So it may not matter.

I see you have the configuration for movies set to delete after a movie has been PLAYED >=365 days ago. As you can see all of these movies were played <1 day ago.

If you are trying to delete movies created >=365 days ago, you need to make the changes below.

```movie_played_days=-1```
```movie_created_days=365```

Please take a look at the examples in the read.me

**Comment by EdeAbreu23** [comment]
Hello @terrelsa13,

i was talking about about the tv shows so they show as keeping but i put 7 days to delete and they are not been deleted even though the played day is 19233 days ago

![image](https://user-images.githubusercontent.com/7027367/187244447-4617b625-d07f-4e77-a2d6-b371ee3950dd.png)

Thanks!

**Comment by terrelsa13** [comment]
@elvis0288 

Without a debug log I have to assume the episodes are not being deleted because some other user has the TV library whitelisted. If another user has the TV library whitelisted and ```multiuser_whitelist_episode=0``` this is why episodes are not being deleted.

I will be able to look into it more once I have a debug log:
1. Set ```DEBUG=4``` in your configuration.
2. Run the script.
3. Attach the ```mumc_DEBUG.log``` to your reply. (Please do NOT copy/paste the contents of the debug log. Please do NOT take a screenshot of the debug log.)

If the debug log file is too large to be attached. Then create a pastebin and include the link to it in your reply.

**Comment by EdeAbreu23** [comment]
if i do debug=4 i get this error
![image](https://user-images.githubusercontent.com/7027367/187262588-e80a51c2-8f59-4c16-9bc5-65f03d74e947.png)

**Comment by terrelsa13** [comment]
Ahh good catch. Looks like I missed passing a variable in for audio/audiobooks. I can fix that once I'm back home later today.

For now disable audio/audiobooks by setting:
* ```audio_played_days=-1```
* ```audio_created_days=-1```
* ```audiobook_played_days=-1```
* ```audiobook_created_days=-1```

Then try again.

**Comment by terrelsa13** [comment]
If this does not work I will have to wait until I am back home and able to fix this before we try again later today.

**Comment by terrelsa13** [comment]
Another option would be to open 'mumc.py' in a text editor and change line #7928 to this:

```appendTo_DEBUG_log("\nkeep_favorites_advanced_audio_book_track_author=" + str(check),2)```

**Comment by EdeAbreu23** [comment]
[mumc_DEBUG.log](https://github.com/terrelsa13/MUMC/files/9446991/mumc_DEBUG.log)

**Comment by terrelsa13** [comment]
Thank you! The debug log makes this much easier and faster for me to see what is going on.

I think I see why this is confusing. I remember you were running the older version of this script; v0 or v1, something like that. On those older versions when you chose libraries (either blacklisted or whitelisted) the non-chosen libraries were discarded; this caused issue later on when trying to determine if another user had the library whitelisted/blacklisted. Since v2, the non-chosen libraries the user has access to, are put into the opposite list.

---------------------------------------------------------------------------------------------------------
So...
If your libraries are: ```movies```, ```tvshows```, ```movies_requested```, and ```tvshows_requested```

**During setup:**
1. You select ```blacklisting```
2. You select ```Johannasanchez168```
3. You select the blacklisted libraries for ```Johannasanchez168``` as ```movies_requested``` and ```tvshows_requested```
4. The non-chosen libraries, ```movies``` and ```tvshows``` are automatically whitelisted

**I can see in the debug log:**
User ```Johannasanchez168``` has ```movies_requested``` and ```tvshows_requested``` blacklisted.
User ```Johannasanchez168``` has ```movies``` and ```tvshows``` whitelisted.

Same for ```erika``` and ```jackeline```.

---------------------------------------------------------------------------------------------------------
If ```Johannasanchez168```, ```erika```, and ```jackeline``` should **NOT** have access to the ```tvshows``` and ```movies``` libraries. 

**The correct way to achieve this is to:**
* Log into jellyfin as the admin
* Go to the "Dashboard"
* Select "Users"
* Select the "Johannasanchez168" account
* Select "Access"
* Uncheck "Enable access to all libraries"
* Only put a check-mark next to ```movies_requested``` and ```tvshows_requested```
* Select "Save"
* Repeat the same steps for ```erika``` and ```jackeline``` accounts

You will have to rebuild the config so the libraries these users should not have access to are not saved as whitelisted.

---------------------------------------------------------------------------------------------------------
If ```Johannasanchez168```, ```erika```, and ```jackeline``` should have access to the ```tvshows``` and ```movies``` libraries.

**Then the correct way to achieve this is to:**
* Open ```mumc_config.py```
* Change ```multiuser_whitelist_episode=0``` to ```multiuser_whitelist_episode=1```
* Save ```mumc_config.py```

---------------------------------------------------------------------------------------------------------
Depending on who should have access to which libraries; either of the solutions above will allow episodes _played 7 or more days ago with a play-count >= 1_ to be deleted.

**Comment by EdeAbreu23** [comment]
@terrelsa13 make sense what you are saying so let me explain to you what i am trying to achieve.

so i have my personal collection which is movies and tvshows. i do not see or have access to the requested movies/shows because that is for people outside my house.

every other person (including a root user) will have access to their requested movies/shows but also my movies/shows. they are both in the same library for them so this is how it looks

ELyLI (ME) 
movies shows and collection

all other users
the movies which include both movies and requested_movies
the tv shows which include both tvshows and requested_tvshows

what i am trying to achieve is that the only person that can delete from the main media would be. so whatever i watch on my main collection will be what will count for the days i selected and delete them accordingly i do not care any other user that watch main movies or shows because that is the media i control.

every other user have ombi and they can request movies which go to the requested folders so i want every other people to be checked on those 2 folders only to delete what they asked for after so many days. 

i remember in your previous version, i was able to create 2 configuration in 2 different folders and then set just me in 1 with the days i want and all that and then set everybody else in another configuration with the days i wanted for them so is this still possible?

Thanks!

**Comment by terrelsa13** [comment]
I see a few ways to achieve what you are trying to do. I am only going to talk about the tvshow libraries to keep the examples short and simple. But the same logic can be applied to movies, audio, and audiobooks.

Also, my **Pros** and **Cons** are based off of how I understand what you are trying to do. What I call a **Pro** you may see as a **Con** and vice-versa.

The below solutions are also not in any particular order.

## Solution 1
In jellyfin give user ```ELyLI``` access to ```movies_requested``` and ```tvshows_requested```.
During setup only select ```ELyLI``` and blacklist the ```tvshows``` library.
To delete played episodes from the ```tvshows``` library after 7 days; set ```episode_played_days=7```, ```episode_played_count_comparison='>='```, ```episode_played_count=1```.
To delete both played and unplayed episodes created 365 days or more ago from the ```tvshows``` and ```tvshows_requested``` libraries; set ```episode_created_days=365```, ```episode_created_played_count_comparison='>='```, ```episode_created_played_count=0```.

**Pros:**
- Only one instance of the script needs to be run
- User management for the script is simplified (only a single user now)
- Episodes in ```tvshows``` are deleted 7 days after they are played
- Episodes in ```tvshows_requested``` are NOT deleted 7 days after they are played

**Cons:**
- Depending on how you watch content you may not be able to hide/filter out the ```tvshows_requested``` library for ```ELyLI```
- Episodes created 365 days ago or more will be deleted from both the ```tvshows``` and ```tvshows_requested``` libraries.

## Solution 2
Keep things setup the way they are now. Change ```multiuser_whitelist_movie=0``` to ```multiuser_whitelist_movie=1```.
To delete played episodes from the ```tvshows``` and ```tvshows_requested``` libraries after 7 days; set ```episode_played_days=7```, ```episode_played_count_comparison='>='```, ```episode_played_count=1```.
To delete both played and unplayed episodes created 365 days or more ago from the ```tvshows``` and ```tvshows_requested``` libraries; set ```episode_created_days=365```, ```episode_created_played_count_comparison='>='```, ```episode_created_played_count=0```.

**Pros:**
- Only one instance of the script needs to be run
- Do not have to hide/filter out the ```tvshows_requested``` library for ```ELyLI```
  - This should be easily done on any media client by only importing the libraries ```ELyLI``` wants to see

**Cons:**
- Script is setup to manage multiple users
- Episodes in ```tvshows``` and ```tvshows_requested``` are deleted 7 days after they are played
- Episodes created 365 days ago or more will be deleted from both the ```tvshows``` and ```tvshows_requested``` libraries.

## Solution 3
Setup two scripts running from different folders. Like you were doing for the older versions.

### Script 1
During setup only select ```ELyLI``` and blacklist the ```tvshows``` library.
To delete played episodes from the ```tvshows``` library after 7 days; set ```episode_played_days=7```, ```episode_played_count_comparison='>='```, ```episode_played_count=1```.

### Script 2
During setup select ```Johannasanchez168``` and whitelist ```tvshows_requested``` library.
Select the same library for ```erika``` and ```jackeline```.
To delete both played and unplayed episodes created 365 days or more ago from the ```tvshows_requested``` library; set ```episode_created_days=365```, ```episode_created_played_count_comparison='>='```, ```episode_created_played_count=0```.

**Pros:**
- User management for the script 1 is simplified (only a single user now)
- Episodes in ```tvshows``` are deleted 7 days after they are played
- Episodes in ```tvshows_requested``` are **NOT** deleted 7 days after they are played
- Episodes in ```tvshows``` are **NOT** deleted after they are created 365 days ago or more
- Episodes in ```tvshows_requested``` are  deleted after they are created 365 days ago or more
- Do not have to hide/filter out the ```tvshows_requested``` library for ```ELyLI```
  - This should be easily done on any media client by only importing the libraries ```ELyLI``` wants to see

**Cons:**
- Script 2 is setup to manage multiple users
- Two instance of the script need to be run

**Comment by EdeAbreu23** [comment]
thank you so much for your options i will probably try 2 and 3 and see which one is better.. i am ok about running 2 instances but i am curious about option 2

Thanks!

**Comment by terrelsa13** [comment]
No problem!

I am going to close this. The original issue, with Trakt's last played dates, is outside of what the script was made to do.

If you run into any other problems, go ahead and open a new issue.

**Comment by terrelsa13** [comment]
Going back to document a new MUMC feature was created to address the Trakt issue.
