### ISSUE TITLE
Request docker installation to make things simplier

### ISSUE THREAD

**Issue by xiNeRoar** [terrelsa13/media_cleaner#40]
i would love to use your plugin but no idea how to install it to my jellyfin server...
can you make it a docker so things will be easier for non-techy?
thanks in advance :)

**Comment by terrelsa13** [comment]
Creating a docker image is something on my todo list for the future. But I currently have no timeline on when I will learn how to create a docker image and then implement it.

I have provided [directions on how to run](https://github.com/terrelsa13/MUMC#first-run-debian-ubuntu-and-linux-mint) this on Debian/Ubuntu/LinuxMint flavors of Linux.

Running a python script in Windows is well documented on the internet. As well as how to install a python module. In this case the python-dateutil module also needs to be installed.

**Edit:** I have updated the READ.ME to give a detailed explanation on how to setup and run a python script in windows.

**Comment by xiNeRoar** [comment]
thanks so much for the explanation. But I have the same concern as him;
https://github.com/terrelsa13/MUMC/pull/20
that we are using a NAS to install all *arr and jellyfin. So trying not to install it directly to my NAS in case of any further change will mess up the whole machine. That's why a dockerize is really helpful in this sense.
Anyway, totally understand and appreciate your work :D keep it up!

**Comment by zilexa** [comment]
Instead of docker, why not simply convert it to a Jellyfin plugin? It's already written in Python. 
This way, it doesn't need to be run in a container. It's just part of Jellyfin plugin library.

**Comment by terrelsa13** [comment]
Yes the a plugin idea could be another path. But there would need to be a plugin for both Emby and Jellyfin.
 - Emby is my main server; the first plugin would be for Emby if I was creating it
 - I would have to make and maintain plugins for both Emby and Jellyfin
 - I do not have the time to maintain MUMC and x2 plugins

If someone else wants to make the frontend for plugins that work with Emby and/or Jellyfin. I would be more than happy to continue supporting the backend mumc.py.

**Comment by zilexa** [comment]
I have zero experience and am not a developer, but did learn python many many years ago. If you would create an Emby plugin, I could perhaps use that as example and fork it for a Jellyfin addon.

**Comment by zilexa** [comment]
Just discovered this, it's not in Jellyfin plugin repository. Will test later:
https://github.com/shemanaev/jellyfin-plugin-media-cleaner

**Comment by aleksasiriski** [comment]
I can make a PR with github workflows for building a docker container on every push and release

**Comment by terrelsa13** [comment]
v5 with docker is on the beta branch.
I have to admit, in my journey to learn and use docker I have discovered I prefer LXCs (to each their own). With that said, v5 is still WIP. Use with caution; YMMV
