### ISSUE TITLE
Multiuser monitored episodes are listed multiple times for deletion

### ISSUE THREAD

**Issue by SenorSmartyPants** [terrelsa13/media_cleaner#43]
I have 2 users that have blacklisted the same directory of episodes. MUMC finds the episodes to delete for each user, but in the summary the total episode count is twice what it should be and episodes to be deleted are listed twice.

Also, I have `multiuser_play_count_episode=1` and that does not seem to affect the age played filtering for both users. Episodes 8-12 should not be deleted because they don't show up in User2's list of episodes to delete. I only want to delete the **intersection** of episodes that each user would delete. 

```
-----------------------------------------------------------
Get List Of Media For:
User1 - 5c0c92019ab2454a8bdcc7aba9abcdd6
-----------------------------------------------------------

:*[DELETE] - Episode - The Daily Show - s28.e01 - Cliff "Method Man" Smith - Comedy Central - Played 53 days ago - Play Count: 5 - Created 53 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: f46838e22ed21d0091bfcb5f6db36fa4
:*[DELETE] - Episode - The Daily Show - s28.e02 - Cori Bush - Comedy Central - Played 47 days ago - Play Count: 1 - Created 53 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 3a100987b11d0893e0a87b40ee555811
:*[DELETE] - Episode - The Daily Show - s28.e03 - Maggie Haberman - Comedy Central - Played 47 days ago - Play Count: 1 - Created 53 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 730a300df51acde23ff9f6c0a89cd342
:*[DELETE] - Episode - The Daily Show - s28.e04 - Constance Wu - Comedy Central - Played 47 days ago - Play Count: 1 - Created 52 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: f20adcad9b3c9f21d6535152d07bca4e
:*[DELETE] - Episode - The Daily Show - s28.e05 - October 11, 2022 - Michael Fanone - Comedy Central - Played 43 days ago - Play Count: 1 - Created 46 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: b51731e0e2273eeff45cf67ff6de5c78
:*[DELETE] - Episode - The Daily Show - s28.e06 - October 12, 2022 - Jon Gray, Pierre Serrao, Lester Walker - Comedy Central - Played 43 days ago - Play Count: 1 - Created 45 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: ec98dffc659a77a4001e413a6ad870e9
:*[DELETE] - Episode - The Daily Show - s28.e07 - October 13, 2022 - Quintessa Swindell - Comedy Central - Played 42 days ago - Play Count: 1 - Created 45 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 24e2b30b4fc3e08c8ad06ab678253b03
:*[DELETE] - Episode - The Daily Show - s28.e08 - October 17, 2022 - Chelsea Manning - Comedy Central - Played 39 days ago - Play Count: 2 - Created 40 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 08dc88907d8b2a19578474cac289ca54
:*[DELETE] - Episode - The Daily Show - s28.e09 - October 18, 2022 - Soledad O'Brien & Amy Schumer - Comedy Central - Played 39 days ago - Play Count: 1 - Created 39 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 25f1754dfe1555ba1c41fc57560720d5
:*[DELETE] - Episode - The Daily Show - s28.e10 - October 19, 2022 - Brandi Carlile - Comedy Central - Played 38 days ago - Play Count: 2 - Created 39 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: b8295a9066bda65843bee0423b51ef18
:*[DELETE] - Episode - The Daily Show - s28.e11 - October 20, 2022 - Tyler James Williams - Comedy Central - Played 35 days ago - Play Count: 1 - Created 38 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 136697f229364bcb8a17cbba4737fe5d
:*[DELETE] - Episode - The Daily Show - s28.e12 - October 24, 2022 - John David Washington - Comedy Central - Played 33 days ago - Play Count: 1 - Created 33 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: e9db6b6ef5cf60ca6d01049a3b0b306d
-----------------------------------------------------------

-----------------------------------------------------------
Get List Of Media For:
User2 - 297752d460c6462c9ed1f4015ea08ad5
-----------------------------------------------------------

:*[DELETE] - Episode - The Daily Show - s28.e01 - Cliff "Method Man" Smith - Comedy Central - Played 50 days ago - Play Count: 1 - Created 53 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: f46838e22ed21d0091bfcb5f6db36fa4
:*[DELETE] - Episode - The Daily Show - s28.e02 - Cori Bush - Comedy Central - Played 49 days ago - Play Count: 1 - Created 53 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 3a100987b11d0893e0a87b40ee555811
:*[DELETE] - Episode - The Daily Show - s28.e03 - Maggie Haberman - Comedy Central - Played 48 days ago - Play Count: 1 - Created 53 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 730a300df51acde23ff9f6c0a89cd342
:*[DELETE] - Episode - The Daily Show - s28.e04 - Constance Wu - Comedy Central - Played 47 days ago - Play Count: 1 - Created 52 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: f20adcad9b3c9f21d6535152d07bca4e
:*[DELETE] - Episode - The Daily Show - s28.e05 - October 11, 2022 - Michael Fanone - Comedy Central - Played 46 days ago - Play Count: 1 - Created 46 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: b51731e0e2273eeff45cf67ff6de5c78
:*[DELETE] - Episode - The Daily Show - s28.e06 - October 12, 2022 - Jon Gray, Pierre Serrao, Lester Walker - Comedy Central - Played 45 days ago - Play Count: 1 - Created 45 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: ec98dffc659a77a4001e413a6ad870e9
:*[DELETE] - Episode - The Daily Show - s28.e07 - October 13, 2022 - Quintessa Swindell - Comedy Central - Played 44 days ago - Play Count: 1 - Created 45 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - EpisodeID: 24e2b30b4fc3e08c8ad06ab678253b03
-----------------------------------------------------------


-----------------------------------------------------------
Summary Of Deleted Media:
* Trial Run Mode
* REMOVE_FILES='False'
* No Media Deleted
* Items = 19
-----------------------------------------------------------
To delete media open mumc_config.py in a text editor:
* Set REMOVE_FILES='True'
-----------------------------------------------------------

[DELETED]   Episode - The Daily Show - s28.e01 - Cliff "Method Man" Smith - f46838e22ed21d0091bfcb5f6db36fa4
[DELETED]   Episode - The Daily Show - s28.e02 - Cori Bush - 3a100987b11d0893e0a87b40ee555811
[DELETED]   Episode - The Daily Show - s28.e03 - Maggie Haberman - 730a300df51acde23ff9f6c0a89cd342
[DELETED]   Episode - The Daily Show - s28.e04 - Constance Wu - f20adcad9b3c9f21d6535152d07bca4e
[DELETED]   Episode - The Daily Show - s28.e05 - October 11, 2022 - Michael Fanone - b51731e0e2273eeff45cf67ff6de5c78
[DELETED]   Episode - The Daily Show - s28.e06 - October 12, 2022 - Jon Gray, Pierre Serrao, Lester Walker - ec98dffc659a77a4001e413a6ad870e9
[DELETED]   Episode - The Daily Show - s28.e07 - October 13, 2022 - Quintessa Swindell - 24e2b30b4fc3e08c8ad06ab678253b03
[DELETED]   Episode - The Daily Show - s28.e08 - October 17, 2022 - Chelsea Manning - 08dc88907d8b2a19578474cac289ca54
[DELETED]   Episode - The Daily Show - s28.e09 - October 18, 2022 - Soledad O'Brien & Amy Schumer - 25f1754dfe1555ba1c41fc57560720d5
[DELETED]   Episode - The Daily Show - s28.e10 - October 19, 2022 - Brandi Carlile - b8295a9066bda65843bee0423b51ef18
[DELETED]   Episode - The Daily Show - s28.e11 - October 20, 2022 - Tyler James Williams - 136697f229364bcb8a17cbba4737fe5d
[DELETED]   Episode - The Daily Show - s28.e12 - October 24, 2022 - John David Washington - e9db6b6ef5cf60ca6d01049a3b0b306d
[DELETED]   Episode - The Daily Show - s28.e01 - Cliff "Method Man" Smith - f46838e22ed21d0091bfcb5f6db36fa4
[DELETED]   Episode - The Daily Show - s28.e02 - Cori Bush - 3a100987b11d0893e0a87b40ee555811
[DELETED]   Episode - The Daily Show - s28.e03 - Maggie Haberman - 730a300df51acde23ff9f6c0a89cd342
[DELETED]   Episode - The Daily Show - s28.e04 - Constance Wu - f20adcad9b3c9f21d6535152d07bca4e
[DELETED]   Episode - The Daily Show - s28.e05 - October 11, 2022 - Michael Fanone - b51731e0e2273eeff45cf67ff6de5c78
[DELETED]   Episode - The Daily Show - s28.e06 - October 12, 2022 - Jon Gray, Pierre Serrao, Lester Walker - ec98dffc659a77a4001e413a6ad870e9
[DELETED]   Episode - The Daily Show - s28.e07 - October 13, 2022 - Quintessa Swindell - 24e2b30b4fc3e08c8ad06ab678253b03
-----------------------------------------------------------


-----------------------------------------------------------
Done.
-----------------------------------------------------------

```

**Comment by terrelsa13** [comment]
In ```mumc_config.py``` please set ```debug=4```, rerun, and attach the ```mumc_DEBUG.log``` that is created.

**Comment by terrelsa13** [comment]
I have locally updated the ```Summary Of Deleted Media:``` to only list each item once.

* I cannot recreate the issue you are seeing with ```multiuser_play_count_episode```
  * When I set this to ```0``` all delete eligible episodes are listed in the ```Summary Of Deleted Media:```
  * When I set this to ```1``` only the overlapping delete eligible episodes are listed in the ```Summary Of Deleted Media:```
  *  I get the same results for both Emby and Jellyfin

Like I mentioned above, I will need your ```mumc_DEBUG.log``` to understand what is different.

**Comment by SenorSmartyPants** [comment]
I have a lot of played files in my libraries, so my log file is rather large. Also, it takes a looong time for mumc to run. on the order of 10 tens of minutes, probably between 20 and 30. I haven't timed it yet (and I didn't notice timestamps in the debug output just now). Have you done any performance testing on large libraries? I play on keeping quite a bit of watched content.

Gziped log file is here https://file.io/KBIOhg9BINMS

**Comment by SenorSmartyPants** [comment]
Maybe this is my issue about what should be deleted or not. I noticed this just now.
`When multiple users are selected; the user with the oldest last played time will determine if media can be deleted.`

So for the 4 Daily Shows that I think shouldn't be deleted, I think that because for User2 last played date isn't greater than 30 days. But it is for User1, so that makes them up for deletion?

My ideal set up would be that for all users that watch a series, all last played dates must be greater than the minimum to be deleted. But I would also like a way to delete episodes when only 1 of 2 users watch a series. Is this currently possible?

**Comment by terrelsa13** [comment]
> So for the 4 Daily Shows that I think shouldn't be deleted, I think that because for User2 last played date isn't greater than 30 days. But it is for User1, so that makes them up for deletion?
This should not be the case when ```multiuser_play_count_episode=1```. Those 4 episodes should not be deleted. I will have time to look more deeply into this over the weekend.


> My ideal set up would be that for all users that watch a series, all last played dates must be greater than the minimum to be deleted.

This is possible if all monitored users are watching a series. It doesn't work if one of the monitored users is not watching the series. Selecting which series' to apply this to could be possible in the future with tags. But for now; when  ```multiuser_play_count_episode=1``` is all or nothing, the script has no way of knowing if a user will never watch a series or if a user just hasn't started watching a series yet. So if user1 watches a series but user2 does not. Episodes from that series should never be deleted.

>But I would also like a way to delete episodes when only 1 of 2 users watch a series. Is this currently possible?

Like I mentioned above. This can be done in the future with tags. For now the only way I can think of achieving your goal is to make three libraries.

* Library1 for shows user1 watches.
* Library2 for shows user2 watches.
* Library 3 for shows user1 and user2 watch.

Then run two instances of MUMC in separate folders.
* The first instance has ```multiuser_play_count_episode=0```.
  * User1 has library1 blacklisted.
  *User2 has library2 blacklisted. 
* The second instance has ```multiuser_play_count_episode=1```
  * User1 has library3 blacklisted
  * User2 has library3 blacklisted

**Comment by SenorSmartyPants** [comment]
Could you add a command line option to specify a config file to use? Then we wouldn't need multiple folders with copies of the apps in each folder.

**Comment by terrelsa13** [comment]
I have opened an issue and tagged it as a feature request. I will start addressing feature requests when I have time in the future to develop them.

> Maybe this is my issue about what should be deleted or not. I noticed this just now.
```When multiple users are selected; the user with the oldest last played time will determine if media can be deleted.```

You are correct. This is where the confusion is coming from. Script is checking played count is met by all users. But not the played days being met by all users. I feel like I have been down this road in the past and there was a reason for this. I just cannot remember if it was before the v3 rewrite or after. Either way I will look into adding a config option to allow selecting if only one user needs to meet the number of days since played or if all need to meet the number of days since played.

**Comment by terrelsa13** [comment]
https://github.com/terrelsa13/MUMC/releases/tag/v3.3.0
