### ISSUE TITLE
Episode processing order

### ISSUE THREAD

**Issue by SenorSmartyPants** [terrelsa13/media_cleaner#44]
I have a lot of series and a lot of episodes in my library. I'm currently testing to make sure I have my config right. But the order of episodes listed on the console is not useful. 

It seems to be Season/Episode and not Series/Season/Episode.

**Comment by SenorSmartyPants** [comment]
I found the issue in Jellyfin at least. You need to use `SeriesSortName` not `SeriesName`

**Comment by terrelsa13** [comment]
Please provide an example of what you mean here.

**Comment by SenorSmartyPants** [comment]
You can see the out of order processing in the log file I attached to #43. After favorite series, it will process all episodes numbered 1x01 first from all series. Then it will do 1x02 from all series, then 1x03 and so on. 

Instead of doing all episodes from Series A, then Series B.

**Comment by terrelsa13** [comment]
Thank you for the debug log. I will have a chance to look into your issues this weekend.

**Comment by terrelsa13** [comment]
Both ```SeriesName``` and ```SeriesSortName``` results are in the same order from my server.

This is the first time I have seen episodes returned in this order:
* Series 1, Season 1, Episode 1
* Series 2, Season 1, Episode 1
* Series 3, Season 1, Episode 1
* Series 4, Season 1, Episode 1
* Series 1, Season 1, Episode 2
* etc...

I agree, the episodes should be ordered like this:
* Series 1, Season 1, Episode 1
* Series 1, Season 1, Episode 2
* Series 1, Season 1, Episode 3
* Series 1, Season 1, Episode 4
* Series 2, Season 1, Episode 1
* etc...

--------------------------------------------------------------------------------------------------------------------------------------

Try the following two API calls and see if these produce episodes returned in different orders.

### SeriesName
```
http://192.168.1.4:8096/emby/Users/5c0c92019ab2454a8bdcc7aba9abcdd6/Items?ParentID=767bffe4f11c93ef34b805451a696a4e&IncludeItemTypes=Episode&StartIndex=0&Limit=100&IsPlayed=True&Fields=Id,ParentId,Path,Tags,MediaSources,DateCreated,Genres,Studios,SeriesStudio,seriesStatus&Recursive=True&SortBy=SeriesName,ParentIndexNumber,IndexNumber,Name&SortOrder=Ascending&EnableImages=False&CollapseBoxSetItems=False&EnableUserData=True&api_key=adc6d74bb62f4d528c8a9732a98be417
```
### SeriesSortName
```
http://192.168.1.4:8096/emby/Users/5c0c92019ab2454a8bdcc7aba9abcdd6/Items?ParentID=767bffe4f11c93ef34b805451a696a4e&IncludeItemTypes=Episode&StartIndex=0&Limit=100&IsPlayed=True&Fields=Id,ParentId,Path,Tags,MediaSources,DateCreated,Genres,Studios,SeriesStudio,seriesStatus&Recursive=True&SortBy=SeriesSortName,ParentIndexNumber,IndexNumber,Name&SortOrder=Ascending&EnableImages=False&CollapseBoxSetItems=False&EnableUserData=True&api_key=adc6d74bb62f4d528c8a9732a98be417
```

**Comment by SenorSmartyPants** [comment]
> Both `SeriesName` and `SeriesSortName` results are in the same order from my server.

Are you running Emby? I run Jellyfin.


> Try the following two API calls and see if these produce episodes returned in different orders.
> 

The sort orders are different. SeriesName is ignored, SeriesSortName works correctly.

In JF you can see that SeriesName is not an option for Item Query sorting.

https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Model/Querying/ItemSortBy.cs

And it makes sense to me to use SeriesSortName since that is what the field is designed to be used for.

**Comment by terrelsa13** [comment]
> Are you running Emby? I run Jellyfin.

I tried on both Emby and Jellyfin. Both returned the same results. So for some reason my JF server is returning series/season/episode order even though it is ignoring SeriesName.

It is easy enough to use SeriesName for JF. But I want to understand why my JF is behaving "correctly" even though it seems like it should not be.

**Comment by terrelsa13** [comment]
Appreciate the assist. But I am only making the ```SeriesSortName``` change for Jellyfin. Emby will continue to use ```SeriesName``` until I get some feedback in the Emby forums about the recommend ```sortBy``` option.

https://github.com/terrelsa13/MUMC/releases/tag/v3.3.0
