### ISSUE TITLE
Empty directories are not deleted

### ISSUE THREAD

**Issue by SenorSmartyPants** [terrelsa13/media_cleaner#51]
When MUMC empties a season or series directory those directories should be removed. Probably should be as an option to remove the directories.

**Comment by terrelsa13** [comment]
This feature request is lower priority.

From what I read in forums and such, the majority of people using emby/jellyfin are also using the *Arrs which has empty directory clean up functionality built into it.

I understand this does not apply to 100% of people. But most have a way to achieve this. Using a program they are already running.

But yes, this would be a good feature add for those not running the above mentioned programs.

**Comment by terrelsa13** [comment]
This also presents an issue of the script having to know when a season or series is finished. Which I have yet to figure out how to determine. Without having to add additional non-emby/non-jellyfin credentials to use an external API.

As I think this through more. This feature becomes less and less desirable to add to this script. I can see issues arising from deleting directories some other program is expecting to drop media items into.

**Comment by SenorSmartyPants** [comment]
That's fine. I'll close this issue and clean up dirs with cli. 

For the record this was on directories made by jellyfin DVR. And I think the DVR and Arrs will just create directors that aren't there, so there's really no need to know if season or series is ended.
