### ISSUE TITLE
Blacktagged episodes not deleting in multiuser system

### ISSUE THREAD

**Issue by SenorSmartyPants** [terrelsa13/media_cleaner#56]
Each user shows correct list of episodes to delete, but nothing is listed in the summary to delete.

Debug log file https://file.io/OpagxbhRTa4L

**Comment by terrelsa13** [comment]
Looks like the debug file is not available anymore. Are you able to re-post it?

I would need to see it in order to determine why it is not working with your configuration vs my configuration.

**Comment by 1cu** [comment]
@SenorSmartyPants You could try creating a new config - this worked for me :-)

**Comment by SenorSmartyPants** [comment]
I created a fresh config (even thou that's what I did in the first place, just getting it all set up) with just one user and it still is not working for me. 

- Single user monitored
- Blacklist - No libraries monitored (so all whitelisted)
- Blacktag - one configured

https://www.file.io/pVdP/download/0kFGjnN3ZMVZ (This log should stay for 2 months)

**Comment by SenorSmartyPants** [comment]
I tested against 3.3.1 and HEAD

**Comment by terrelsa13** [comment]
@SenorSmartyPants You are correct. Legit bug. Fixed on local. Will let you know when pushed to GitHub.

**Comment by SenorSmartyPants** [comment]
Any ETA on when you'll push this fix? I don't need a full release just the commit will work for me.

**Comment by terrelsa13** [comment]
Apologies, thank you for being patient. Started making changes, including the fix for blacktagged items, then had to leave town for work. I am back home, but now need to take care of family business before I can vet the changes. I estimate Friday before I can push anything to GitHub.

Again, apologies for the delay.

**Comment by SenorSmartyPants** [comment]
No problem. Real life takes priority.

**Comment by terrelsa13** [comment]
@SenorSmartyPants Thank you for your patience! It is very much appreciated.

Just pushed [v3.3.3](https://github.com/terrelsa13/MUMC) to the trunk. It should address the issue with whitelisted media items not being deleted when they are blacktagged.

Let me know how this works out.

**Comment by SenorSmartyPants** [comment]
Looks like this is fixed. Correct list of episodes in delete summary (haven't actually deleted them yet)
