### ISSUE TITLE
Warning Notifications on media deletion

### ISSUE THREAD

**Issue by bandundu** [terrelsa13/media_cleaner#58]
Hi, I would really love to have the Feature of notifying users of future media deletion. I'm running a jellyfin server with multiple users and would like to inform users of incoming media deletion x days beforehand by mail or telegram bot to incentivize them to either watch the media or favorite them to keep sure they don't get deleted.

**Comment by terrelsa13** [comment]
Hey @bandundu I have no plans on adding a feature like this to the script. But I do have a few suggestions that may get you similar behavior.

1. Let users know the played/created days they have before deletion. For instance if ```played_days_movie=31``` and ```created_days_movie=365```. Let the users know they have 31 days after a movie is watched before it is deleted and 365 days after it is downloaded before it is deleted.
2. Let users know they must favorite media items they want to keep. This will allow them to proactively prevent media items they plan on watching from being deleted.
3. MUMC provides an output with the data needed for you to write a script that parses the MUMC output and uses that to notify each user of the media items that will be deleted soon.

Hopefully this helps.
