### ISSUE TITLE
Expand delete media after all users viewed to look at series

### ISSUE THREAD

**Issue by selfdigest** [terrelsa13/media_cleaner#59]
Hi, this is a great script, and the new feature in 4.0 ( #55 ) is working great, except for one issue for me. (unless I'm missing something)

Can an option be added to monitor series favorites?

Eg; Right now, users would have to favorite each episode for it to be triggered. 
I'd like it to allow users to favorite just a series, and it monitor the episodes as if they were all favorites.

Also, thank you. This script is actually making it where I can finally move from plex. 👍

**Comment by terrelsa13** [comment]
Hey @sek0n thanks for catching this. I have pushed a fixed for the issue to the trunk with v4.0.4-beta.

Favorites should now work. If a series is set as a favorite the child seasons and episodes will also be considered favorites.
