### ISSUE TITLE
Blacktagged episodes not deleting when any user watched

### ISSUE THREAD

**Issue by SenorSmartyPants** [terrelsa13/media_cleaner#60]
I set up a black tag to use when only one user watches something and a config to delete black tagged shows when any user has watched it. MUMC correctly lists episodes to delete under the user that watched them, but there is a monitored user who doesn't watch this show (I want to use the same solo black tag for any user) and no episodes are chosen for deletion in the summary.

debug log is [here](https://www.file.io/L2M8/download/rpTgyKAAb3Z3)

**Comment by terrelsa13** [comment]
Looks like you were running v3.3.0.

Try running the latest on the trunk v3.3.5.

**Comment by SenorSmartyPants** [comment]
Same behavior running trunk v3.3.5 [debug log](https://www.file.io/mhtA/download/EXR9r4zzt8kl)

**Comment by terrelsa13** [comment]
```minimum_number_played_episodes=1``` is the culprit. I am looking into why all episodes are being removed from the delete list vs. all but the latest watched episode being removed from the delete list.

**Comment by terrelsa13** [comment]
Try v3.3.6 on the trunk.
You may also have to play around with ```minimum_number_episodes_behavior'```
Try starting with ``minimum_number_episodes_behavior='Max Played Min Unplayed'``

**Comment by SenorSmartyPants** [comment]
I tried trunk and got same behavior. But `minimum_number_episodes_behavior='Max Played Min Unplayed'` did the trick.

If I understand correctly, The first option(`Max Played`) in `minimum_number_episodes_behavior` controls the `minimum_number_episodes` behavior, and the second part of the string (`Min Unplayed`) controls `minimum_number_played_episodes`

**Comment by terrelsa13** [comment]
> If I understand correctly, The first option(Max Played) in minimum_number_episodes_behavior controls the minimum_number_episodes behavior, and the second part of the string (Min Unplayed) controls minimum_number_played_episodes

These apply to the number of played and unplayed episodes that will be deleted.

If a User Name/Id is specified the script will delete/keep episodes based off that specific user. And this works fine when there is a single user or multiple users are watching the same show at the same speed.

When multiple users are watching the same show at different speeds; the script needed a way to allow specifying if the slowest watcher or the fastest watcher should determine how many episodes are deleted. This is where ```Max/Min Played/Unplayed``` comes in. You can specify just a single ```Max Played``` and this will delete episodes based off the first user with the highest number of played episodes, ```Max Unplayed``` would delete based off of the first user with the highest number of unplayed episodes, etc...

To allow a little more flexibility ```Max/Min Played/Unplayed``` can be paired together. So the number of played/unplayed episodes would be based off of the user(s) with the ```Max/Min``` ```Played/Unplayed``` episodes, allowing a kind of hybrid of the fastest and slowest users watching a show.
