### ISSUE TITLE
[Feature] Add the ability to delete media on Radarr & Sonarr

### ISSUE THREAD

**Issue by Floflobel** [terrelsa13/media_cleaner#61]
Hello,

Do you think it would be possible to add deleting also on Radarr and Sonarr?

The problem is that if a media is deleted on Emby while it is linked to Sonarr / Radarr then it will try to re-download it.

I saw that your script retrieves the media ID on Emby but it doesn't seem to retrieve the ID that Sonarr and Radarr handles: IMDB & TVDB.

If already in the output I could get the IMDB and TVDB id I would be able to do it myself on my side.

Thanks in advance.

**Comment by terrelsa13** [comment]
Hey @Floflobel 
Go to ```Sonarr > Settings > File Management``` and check mark ```Unmonitor Deleted Episodes```. Save this change.
This will prevent Sonarr from re-downloading deleted media items.
Radarr has the same setting.

**Comment by terrelsa13** [comment]
Finally found the time to tie into the Radarr & Sonarr APIs to handle this more gracefully.

#132 - Unmonitor Movies & Episodes In Radarr & Sonarr After Deletion
#133 - Option To Remove Movie Entries & Series Entries From Radarr & Sonarr After MUMC Deletion

Release v5.10.0-beta or later.
