### ISSUE TITLE
Favorite filter not working, or honoring priority

### ISSUE THREAD

**Issue by selfdigest** [terrelsa13/media_cleaner#62]
I have the latest v4 beta. Testing it out with my new server setup, and it seems to either not honor the priority, or just isn't working.

Also a chance I've misunderstood the settings and messed it up myself.

What is happening:
User 1: Confirmed to have favorited the series.
User 2: Confirmed to have favorited the series.

User 1: Watched episodes 1-5 of the series.
User 2: Watched episode1, and 8 in the same series.

Result: Episodes 1-5, and 8 are deleted.

Blacklist as default, rest of the settings are set to default as well, besides the below:

```
played_filter_episode=[0, '>=', 1]
...
favorited_behavior_episode=['delete', 'any', 'all', 3]
```
I've also tried with different X and Y settings, but no change.

Switched the default to whitelist, and setup the users again. I doesn't delete anything with that set.

**Comment by terrelsa13** [comment]
@sek0n In the config file set ```DEBUG=4``` then run the script so the issue happens.

In the folder that has the ```mumc.py```script there will be a filed called ```mumc_DEBUG.log```.
Either attach the file to your reply OR use something like [https://pastebin.com/](https://pastebin.com/) or [https://www.file.io/](https://www.file.io/) to upload the file. Then reply back with the link.

The ```mumc_DEBUG.log``` will allow me to see what the script is doing to help figure out if there is an issue or if my default settings are causing confusion.

**Comment by terrelsa13** [comment]
I think I see what is happening. Try changing the ```3``` to a ```5```.

Looks like there are some common use cases where ```5``` should be the recommended ```Action Control```.

**Comment by terrelsa13** [comment]
Looks like I also have some issues with printing the json data to debug. So ```DEBUG=4``` won't work right now anyway.

But what I mentioned before about changing ```3``` to ```5``` should set you on the right path.

**Comment by selfdigest** [comment]
Ok, I did as you said. With 5, only episode 8 is deleted now.

I updated to the new version that was updated a little bit ago, then did the debug in-case the debug was fixed.

Set to 5: [mumc_DEBUG.5.log](https://github.com/terrelsa13/MUMC/files/10378609/mumc_DEBUG.5.log)
Set to 3: [mumc_DEBUG.log](https://github.com/terrelsa13/MUMC/files/10378610/mumc_DEBUG.log)

**Comment by terrelsa13** [comment]
I have not forgotten about this; bigger change than expected. I am working on a fix. Likely going to be this weekend when I have something.

**Comment by terrelsa13** [comment]
Updates pushed to [v4 branch](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA). Give v4.0.10-beta a try with ```favorited_behavior_episode=['delete', 'any', 'all', 5]```

Tried this on my setup and only episode 1 deleted; as expected.

**Comment by selfdigest** [comment]
It's working now, partially.

Did as you said; it deletes the correct episode, but now only if **every** user has it watched. Even users that don't have it favorited.

Ex;
User 1: Favorited+watched
User 2: Favorited+watched
User 3: not favorited or watched
Doesn't Delete

Ex;
User 1: Favorited+watched
User 2: Favorited+watched
User 3: not favorited, but watched
Deletes the correct episode.

Also noticed with this update, when changing `played_filter_movie=[-1, '>=', 1]` to anything besides -1, it throws this error:

```
Traceback (most recent call last):
  File "/opt/mumc/./mumc.py", line 9821, in <module>
    deleteItems=get_media_items()
  File "/opt/mumc/./mumc.py", line 5767, in get_media_items
    isblacklisted_and_played_byUserId_Movie=parse_actionedConfigurationBehavior(item,user_key,'blacklisted',isblacklisted_and_played_byUserId_Movie,blacklisted_behavior_movie,item_isBlackListed,item_matches_played_days_filter,item_matches_played_count_filter)
TypeError: parse_actionedConfigurationBehavior() missing 1 required positional argument: 'item_matches_played_count_filter'
```

**Comment by terrelsa13** [comment]
Updates pushed to [v4 branch](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA). Give v4.0.12-beta a try

**Comment by selfdigest** [comment]
Getting this when it gets to the processing part:

```
POST PROCESSING STARTED...
Traceback (most recent call last):
  File "/opt/mumc/./mumc.py", line 9854, in <module>
    deleteItems=get_media_items()
  File "/opt/mumc/./mumc.py", line 7777, in get_media_items
    isfavorited_and_played_byUserId_Episode,isfavorited_extraInfo_byUserId_Episode=favorites_playedPatternCleanup(isfavorited_and_played_byUserId_Episode,isfavorited_extraInfo_byUserId_Episode,episode_played_days,episode_created_days,cut_off_date_played_episode,cut_off_date_created_episode,episode_played_count_comparison,episode_played_count,episode_created_played_count_comparison,episode_created_played_count,favorited_behavior_episode,favorited_advanced_episode_genre,favorited_advanced_season_genre,favorited_advanced_series_genre,favorited_advanced_tv_library_genre,favorited_advanced_tv_studio_network,favorited_advanced_tv_studio_network_genre)
  File "/opt/mumc/./mumc.py", line 4613, in favorites_playedPatternCleanup
    if (itemIsFav or itemIsAdvFav):
UnboundLocalError: local variable 'itemIsAdvFav' referenced before assignment
```

**Comment by terrelsa13** [comment]
Try the latest v4. Let me know if this is doing what you expect.

**Comment by selfdigest** [comment]
Yep, that seems to have done it. Looks like it's working as expected now.

Thanks!
