### ISSUE TITLE
Version info mumc_config.py

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#66]
My update scheme was to only update the mumc.py unless specified otherwise. Lately I ran into some changes which do reflect changes in the mum_config.py

Would it be helpful if the mumc_config.py could get some version info. Maybe the version of the mumc.py which created it. Therefor it would be possibly to alert that the mumc_config.py needs to be upgraded/recreated.

**Comment by terrelsa13** [comment]
Yeah, I can see how this could be an issue/frustrating. My thought here was the ```beta``` was a good indicator "breaking" changes might still be happening.

Once I remove the ```beta``` I try my best to avoid breaking changes with the config.

But yes, this is a good idea. I will have to think about how to implement this.

**Comment by terrelsa13** [comment]
There is no clean way from me to implement this until the next major version change (aka v5). Which is likely a year or so away. But I will keep this feature request open so I do not forget about it and can start laying the ground work beforehand.

**Comment by terrelsa13** [comment]
An 85% complete v5 is on the beta branch. Config versioning has been implemented with v5.
