### ISSUE TITLE
Option to move files rather than delete

### ISSUE THREAD

**Issue by KaiboshOz** [terrelsa13/media_cleaner#70]
Subject pretty much says it all.. Feature request to move all matching files into a defined directory rather than delete them.

Having had this feature in another application (Kodi addon Janitor) prior to moving to Emby, I found it extremely useful - to the point that I had an instance of Kodi setup linked to my Emby instance solely to use that addon to cleanup files.

I was able to run it regularly, moving old files to a directory outside of my libraries, eliminating the paranoia (that I'm sure we'll all had at one time or another) of deleting files since they still exist and are just moved.
When diskspace starts becoming an issue, I have a look at the files in that "moved" directory; make sure nothing looks unusual, like hundreds of tv episodes that I know I haven't watched; and then delete everything in the "moved" directory.

It also acts as a safety net in case I've messed up the filter, or in the very unlikely event that some bug happened to make it into MUMC that potentially deleted more than the filter was supposed to.

**Comment by terrelsa13** [comment]
This might be a possible feature if...

1. MUMC can change a file's path (location) via the Emby/Jellyfin API.
2. I am willing to bet if Emby/Jellyfin can do 1; then the new path will need to be a folder Emby/Jellyfin knows about and has access to.

Everything MUMC does is through Emby/Jellyfin. I will not implement any features to movie/modify/delete media items directly (aka outside of the Emby/Jellyfin API).

It will be a few months until I have the time to implement this.

**Comment by KaiboshOz** [comment]
I didn't consider that the move would need to be done through Emby/Jellyfin, but it makes perfect sense after you pointed it out.

Appreciate the quick reply and am hopeful that it's doable at some point down the line!

**Comment by terrelsa13** [comment]
@KaiboshOz Been trying to find a way to make this happen. From what I can find, the closet way to achieve this is to perform the following steps:

[How to Move Your Library to Another Location](https://emby.media/community/index.php?/topic/78123-how-to-move-your-library-to-another-location/) - This would also apply to individual media items.
1. Stop emby (which also stops the API)
2. Modify the library.db, via the OS command line or a database editor
3. Restart emby

--------------------------

[Question: How to change metadata manager path](https://github.com/MediaBrowser/Emby/issues/2524)
 - It looks like changing the metadata path does not change the physical path location. Even after changing the metadata path, the physical files need to be moved via the file system/OS, and then a library scan performed.

--------------------------

Unfortunately does not appear this can be done via the API. For now I am closing this request as "not planned". If someone smarter and better at Googling than me figures out how to do this via the emby/jellyfin API I would be more than happy at trying to implement this feature.
