### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by zilexa** [terrelsa13/media_cleaner#72]
Before first run, I changed this in the defaults file: 
```
        'played_filter_movie':[3,'>=',1],
        'played_filter_episode':[21,'>=',1],
        'played_filter_audio':[-1,'>=',1],
        'played_filter_audiobook':[7,'>=',1],
```
I only have movies and tvshows in Jellyfin btw. 
Then I run for the first time, select Jellyfin, enter credentials and choose ALL defaults (simply hitting enter):

```
python3 $HOME/docker/HOST/mediacleaner/mumc.py                              INT ✘  50s  
-----------------------------------------------------------
Version: 4.1.18-beta
-----------------------------------------------------------
0:emby
1:jellyfin
Enter number for server branding (default emby): 1
-----------------------------------------------------------
Enter server ip or name (default http://localhost): 192.168.88.2
Assuming server ip or name is: http://192.168.88.2
-----------------------------------------------------------
If you have not explicity changed this option, press enter for default.
Space for no port.
Enter port (default 8096): 
-----------------------------------------------------------
If you have not explicity changed this option in jellyfin, press enter for default.
For example: http://example.com/<baseurl>
Enter base url (default /emby): 
-----------------------------------------------------------
Enter admin username: myusername
-----------------------------------------------------------
Plain text password used to grab authentication key; password not stored.
Enter admin password: mypassword
-----------------------------------------------------------
Decide how the script will use the libraries chosen for each user.
0 - blacklist - Chosen libraries will blacklisted.
                All other libraries will be whitelisted.
1 - whitelist - Chosen libraries will whitelisted.
                All other libraries will be blacklisted.
Choose how the script will use the chosen libraries. (default blacklist): 
-----------------------------------------------------------
Decide how the script will match media items to libraries.
0 - byId - Media items will be matched to libraries using 'LibraryIds'.
1 - byPath - Media items will be matched to libraries using 'Paths'.
2 - byNetworkPath - Media items will be matched to libraries using 'NetworkPaths'.
   If your libraries do not have a 'Shared Network Folder' you must filter byPath.
   If your libraries have a 'Shared Network Folder' you must filter byNetworkPath.
   Filtering byId does not have the above limitations.
Choose how the script will match media items to libraries. (default byId): 
-----------------------------------------------------------
Enter the desired blacktag name. Do not use backslash '\'.
Use a comma ',' to seperate multiple tag names.
 Ex: tagname,tag name,tag-name
Leave blank to disable the blacktagging functionality.
Input desired blacktags: 
-----------------------------------------------------------
Enter the desired whitetag name. Do not use backslash '\'.
Use a comma ',' to seperate multiple tag names.
 Ex: tagname,tag name,tag-name
Leave blank to disable the whitetagging functionality.
Input desired whitetags: 
-----------------------------------------------------------


Exception When Selecting User. Try again.

-----------------------------------------------------------
-----------------------------------------------------------
-----------------------------------------------------------
* Config file is not setup to delete media.
* Config file is in dry run mode to prevent deleting media.
-----------------------------------------------------------
To delete media open mumc_config.py in a text editor:
* Set REMOVE_FILES='True'
-----------------------------------------------------------
*Edit the mumc_config.py file and try running again.
-----------------------------------------------------------
```

Note the " Exception When Selecting User. Try again" . My user credentials are valid though. 
when I run again, I get this: 
```
python3 $HOME/docker/HOST/mediacleaner/mumc.py
-----------------------------------------------------------

-----------------------------------------------------------
MUMC Version: 4.1.18-beta
Jellyfin Version: 10.8.9
Python Version: 3.10.9
Time Stamp: 20230227215536
-----------------------------------------------------------

-----------------------------------------------------------
Start...
Cleaning media for server at: http://192.168.88.2:8096/emby
-----------------------------------------------------------

Traceback (most recent call last):
  File "/home/asterix/docker/HOST/mediacleaner/mumc.py", line 8565, in <module>
    deleteItems_movie=run_post_processing(config_dict,movie_dict)
  File "/home/asterix/docker/HOST/mediacleaner/mumc.py", line 6029, in run_post_processing
    mediaType=media_dict['mediaType']
KeyError: 'mediaType'
```

**Comment by terrelsa13** [comment]
> ```Exception When Selecting User. Try again.```

The script does not seem to have made it to where it asks to select users to monitor.

During the setup; after the ```whitetags``` section it should show the list of users to choose from:
```
0 - user0 - fcc07abc1d8047458d2e3ca459e8cb0a
1 - user1 - 64fb67457eabc4a0bfcbad4e957f381e
2 - user2 - 8a067b3b3a8cbaabc57a98f8c2cfea26
3 - user3 - d3a1cbcbaced4f7a85a88abc47ac1539
4 - user4 - cbac4def2d8548f4b383110f5624ab4c

Select one user at a time.
Enter number of the user to monitor:
```
Going to need you to attach a couple files in your reply.

First attach your config file.
Second attach a DEBUG file. To create the DEBUG file follow the steps below.

1. Open the config file and set ``DEBUG=4```
2. Rerun the script so the error happens
3. In the same folder the config file is in there should now be a file called ```mumc_DEBUG.log```
4. Attach the ```mumc_DEBUG.log``` file along with the config file to your reply

**Comment by zilexa** [comment]
Correct, I also expected user selection, but that doesn't appear: 

Mumc config: https://pastebin.com/SNPYd0fd
Mumc debug log: https://pastebin.com/PGzUAymX

**Comment by terrelsa13** [comment]
I found the issue. I never run the 'single' user portion of the user and library builder. I always have multiple users. Looks like when I first released v4 I made a copy/paste error. I have fixed this and updated the v4 trunk with [v4.1.19-beta](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA).

1. Delete the current config
2. Re-run the script
3. Let me know if this fixes the issue

**Comment by zilexa** [comment]
Thanks it works now!
May I suggest following github common standards? 
Your page https://github.com/terrelsa13/MUMC still points to an old version. But in the readme you point to a BETA version..
This is actually a separate repository instead of proper fileversioning. 
It seems you are applying a methodology often used in large corporations for more traditional large scale IT projects. Especially with the extended support etc. There is no such thing, is there? You can always have multiple branches without affecting your main branch (which clearly seems to be v4BETA). Might save you some time and make it more clear for users to just have a generic repository " https://github.com/terrelsa13/MUMC "  this will also ensure temporary URLs like " https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA "  don't get lost.. or are not necessary in the first place. Versioning in a URL is not really a good idea. Just my 2 cents.

Edit: short version of what I mean is your non-testing version would be expected to be this file: 
https://github.com/terrelsa13/MUMC/blob/master/mumc.py, not a constantly changing URL (v3, v4BETA, probably v4 is next), each time making the previous URL point to a version you no longer recommend in your readme.md ;)

**Comment by terrelsa13** [comment]
- v3 is still the "production" default branch.
- v4 is in beta phase.

Once v4 leaves beta it will become default and v3 will become a historical branch like v2. But I don't want to point everyone to the v4 branch until I have some confidence bugs like the one you encountered have been found and fixed.

**Comment by zilexa** [comment]
Ok sounds great. But still, the default production branch has versioning in its URL.. that's my point. 
Versioning in a URL is very unusual..

**Comment by terrelsa13** [comment]
The default/main branch is [https://github.com/terrelsa13/MUMC](https://github.com/terrelsa13/MUMC) until the end of March. No versioning in the URL.

[https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA](https://github.com/terrelsa13/MUMC/tree/MUMC_v4-BETA) is not the default/main branch **yet**. But it will be after March 31st.

Am I still missing what you are suggesting?

**Comment by zilexa** [comment]
To download the 2 required files on my server, I log into SSH and use wget. I actually have a script to take care of this for easy initial server setup. But in both cases I would have to use:

https://github.com/terrelsa13/MUMC/blob/MUMC_v3/mumc.py

Which means if I want to update my parents server next week I might have to double check the URL because it could well be different, latest default recommended could be v4. 
With every upcoming default version, the URL will be different. Why? GitHub made it real easy to prevent this.

Any other github (or gitlab) tool is usually simply to be found via the master link instead (which could be V3 if you intend that to be).

https://github.com/terrelsa13/MUMC/blob/master/mumc.py

**Comment by terrelsa13** [comment]
Ahhh ok! I follow you now. I can fix that once v4 becomes the default. Thanks for pointing that out!

**Comment by zilexa** [comment]
Great thanks!
