### ISSUE TITLE
Not evaluating movies 

### ISSUE THREAD

**Issue by zilexa** [terrelsa13/media_cleaner#75]
Mumc v4 is not evaluating movies.

**Comment by terrelsa13** [comment]
Please set ```debug=4```, run script of the issue happening, and send the log that is created.

**Comment by terrelsa13** [comment]
@zilexa Is this still an issue for you? I was never able to reproduce it on my end; and never saw a debug log to help diagnose the problem.

**Comment by terrelsa13** [comment]
@zilexa I have not received a response about how to help you. I am closing this issue.
