### ISSUE TITLE
Look Into Making This An Emby (Jellyfin) Add-On

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#76]
If time permits and this is not a big task; look into creating an Emby add-on.

Idea from #40 

### Concerns:
 1. The number of options in config that will need to be changable in the GUI.
 2. Jellyfin is not my main. So someone else would need to create/modify/maintain the JF add-on

**Comment by aleksasiriski** [comment]
Would python plugin work? Wouldn't it need to be C#?

I can make a PR with github workflows for building a docker container on every push and release

**Comment by terrelsa13** [comment]
I skimmed thru "how to make an emby plug-in" and the examples I saw did appear to be in C#. But I didn't do a deep dive to understand if there is a way to make a plug-in from python code.

If you are able to make a pull request to have a docker build created for each push and release that would be awesome!

**Comment by aleksasiriski** [comment]
Before I can finish my docker work, could you decouple the config generation into a seperate python script?

So that main `mumc.py` only searches for the config, and a seperate `mumc_generate_config.py` asks all of the questions?

Also I would suggest that you switch to yaml for the config file, you can take a look [here](https://github.com/joshuaboniface/rffmpeg/blob/master/rffmpeg#L117) on how to do it.

After that I can make the addition to use asyncio to run the program indefinitely with an also configurable timeout, alleviating the need to use cronjobs.

**Comment by aleksasiriski** [comment]
Also a nice to have would be to use Jellyfin API key if possible, instead of the current method, but that's optional.

**Comment by aleksasiriski** [comment]
We may continue this discussion [here](https://github.com/terrelsa13/MUMC/pull/77)

**Comment by xiNeRoar** [comment]
Is this plugin development still alive?

**Comment by terrelsa13** [comment]
> Is this plugin development still alive?

Yes, I am still developing this. Life has been crazy. I will admit I have been neglecting v4 and instead spending the time I can find on v5. Goal is for v5 to have a docker option instead of becoming an Emby/Jellyfin plugin. v5 I am also working to address the other open issues.

**Comment by terrelsa13** [comment]
There is a 85% working v5 in the beta branch.
The config editor and config converter from the legacy config format to the new yaml format are WIP. There are also several configuration option values that have not been confirmed as working.

**Comment by xiNeRoar** [comment]
> There is a 85% working v5 in the beta branch. The config editor and config converter from the legacy config format to the new yaml format are WIP. There are also several configuration option values that have not been confirmed as working.

may i ask how to use it as a plugin in jellyfin? usually other plugin have to put a json link in jellyfin to make it work. where can i find the json link for mumc?

**Comment by terrelsa13** [comment]
> Goal is for v5 to have a docker option instead of becoming an Emby/Jellyfin plugin.

There is no plug-in. There is a docker option for v5 in the beta branch.
