### ISSUE TITLE
Option to delete subtitle file

### ISSUE THREAD

**Issue by AussieAbroad** [terrelsa13/media_cleaner#79]
Is it possible to also delete any subtitle files associated with the movie or episode "  .srt " when it deletes video?

**Comment by terrelsa13** [comment]
@AussieAbroad I am looking into this. Not having any luck with Emby/Jellyfin giving me the subtitle information associated to a media item.

**Comment by terrelsa13** [comment]
I am not able to find an API facing option for the script to specifically delete subtitles associated with a movie/episode available with Emby/Jellyfin.

Any media file manipulation MUMC does is through the Emby/Jellyfin API. I will not implement any features to move, modify, or delete media items directly (aka outside of the Emby/Jellyfin API).

Unless someone else knows of a way to associate specific subtitle files to a media item; this will be closed as "not planned".
