### ISSUE TITLE
Filters based on LibraryID

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#84]
I recently created a third library. For this library with movies I want a different set of filters then for my other library with movies. I tried to accomplish this with the current set of filters but i'm cant figure it out.

The only way I can think of is a second instance of MUMC or a second run with another configfile.

Is this something than can be done in a next release?

**Comment by terrelsa13** [comment]
Hey @keppo070. You are correct, the best way to accomplish this is to create an ```alternate_config.py``` and then run the script using the ```-c``` option.

It will look like this: ```/path/to/python3.11 /path/to/mumc.py -c /path/to/alternate_config.py```

**FYI**
#### These are NOT valid config file names:
 - /path/to/alternate.config.py
 - /path/to/alternate config.py
 - c:\\path\\to\\alternate.config.py
 - c:\\path\\to\\alternate config.py

#### These are valid config file names
 - /path/to/alternateconfig.py
 - /path/to/alternate_config.py
 - c:\\path\\to\\alternateconfig.py
 - c:\\path\\to\\alternate_config.py

Let me know if you have any other questions.

**Comment by keppo070** [comment]
I created an new mumc_config.py for 1 library containing only 2 movies. When running MUMC it also checks not configured library. Also epsiodes.

I would expect that only the configured library would be checked.

**Comment by terrelsa13** [comment]
I will need to see how your config is setup.

Keep in mind the libraries not selected are put into the other bucket. For example if "blacklisting" is chosen then the libraries not selected are all considered whitelisted.

If the config settings are telling the script to check the whitelisted libraries it will look in the whitelisted libraries.

Using the example above, there is currently no option to skip adding the not selected libraries to the whitelist bucket. They can be manually removed from the config.

**Comment by terrelsa13** [comment]
@keppo070 I have been working on v5 of MUMC. It will have the ability to enable/disable specific libraries for specific users. This should allow you to do whatever you were looking to do a few months ago.

v5 is still in development and will move to the latest branch once a few more things have been addressed.
