### ISSUE TITLE
UnboundLocalError: cannot access local variable 'tvstudionetwork_item_info' where it is not associated with a value

### ISSUE THREAD

**Issue by twicehopped** [terrelsa13/media_cleaner#85]
Running into this issue when scanning my entire library:

> Traceback (most recent call last):
>   File "C:\Users\***\MUMC\MUMC\mumc.py", line 8591, in <module>
>     episode_dict,episode_found=get_media_items('episode',config_dict,episode_dict,user_key)
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\***\MUMC\MUMC\mumc.py", line 5936, in get_media_items
>     item_isBlackTagged=get_isEPISODE_Tagged(item,user_key,blacktags)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\***\MUMC\MUMC\mumc.py", line 3196, in get_isEPISODE_Tagged
>     istag_EPISODE['seriesstudionetwork'][tvstudionetwork_item_info['Id']],tagged_items=get_isItemTagged(usertags,tagged_items,tvstudionetwork_item_info)
>                                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
> UnboundLocalError: cannot access local variable 'tvstudionetwork_item_info' where it is not associated with a value

Config attached with keys removed. 
[mumc_config - Copy.txt](https://github.com/terrelsa13/MUMC/files/12096946/mumc_config.-.Copy.txt)

**Comment by terrelsa13** [comment]
Was using a variable before it was assigned a value. Should be fixed in the latest. v4.1.23

**Comment by twicehopped** [comment]
Thanks! Is 4.1.23 published?

**Comment by terrelsa13** [comment]
It is on the [MUMC_Latest](https://github.com/terrelsa13/MUMC) branch.

And is now the latest [release](https://github.com/terrelsa13/MUMC/releases) as well.

**Comment by twicehopped** [comment]
Using 4.1.24 and ran into this issue (I think in a different line of code):

Traceback (most recent call last):
  File "C:\Users\*\MUMC\MUMC\mumc.py", line 8597, in <module>
    episode_dict,episode_found=get_media_items('episode',config_dict,episode_dict,user_key)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\MUMC\MUMC\mumc.py", line 5942, in get_media_items
    item_isBlackTagged=get_isEPISODE_Tagged(item,user_key,blacktags)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*\MUMC\MUMC\mumc.py", line 3199, in get_isEPISODE_Tagged
    if (tvstudionetwork_item_info):
        ^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'tvstudionetwork_item_info' where it is not associated with a value

**Comment by wangrui1573** [comment]
:[KEEPING] - Episode - 机动战士高达：水星的魔女 - s01.e10 - 旋绕于心的想法 - MBS - Played 270 days ago - Play Count: 1 - Created 105 days ago - Favorite: False - WhiteTag: False - BlackTag: False - Whitelisted: False - Blacklisted: False - EpisodeID: 41147
Traceback (most recent call last):
  File "mumc.py", line 8597, in <module>
    episode_dict,episode_found=get_media_items('episode',config_dict,episode_dict,user_key)
  File "mumc.py", line 5922, in get_media_items
    item_isWhiteTagged=get_isEPISODE_Tagged(item,user_key,whitetags)
  File "mumc.py", line 3199, in get_isEPISODE_Tagged
    if (tvstudionetwork_item_info):
UnboundLocalError: local variable 'tvstudionetwork_item_info' referenced before assignment

same problem with last [MUMC v4.1.24](https://github.com/terrelsa13/MUMC/releases/tag/v4.1.24)

**Comment by terrelsa13** [comment]
@wangrui1573 @twicehopped My apologies, life and work has been busy. I have not had a lot of time to spend on v4 of this script. And anytime I do have, I use it toward making improvement in v5 of the script.

I have fixed all places in the tagged and favorited functions where the variable was used before it was defined in v5.
v5 is not ready for the latest branch, but it is mostly functional and available in the beta branch.
