### ISSUE TITLE
How to select all Users ?

### ISSUE THREAD

**Issue by GautierT** [terrelsa13/media_cleaner#87]
Hi !
Thanks a lot for this awesome script !

I would like to select all Users to apply to them the same settings. Is it possible ? When running the script I'm asked to choose user one by one. Is it possible to select them all ?

To be able to say : **if** none of the users played a content in the last 400 days **and** the file as been created more than 400 days **then** delete

Thanks.

**Comment by terrelsa13** [comment]
Unfortunately you will need to select each user individually.
You can however select all libraries. For instance, if you want all libraries black listed then choose whitelisting as the behavior and then do not select any libraries when prompted. This will blacklist all libraries for that user.

**Comment by terrelsa13** [comment]
@GautierT I have been working on cleaning up the user and library builder so those with either many libraries or many users can create/edit the users and libraries more efficiently. In your case, you asked if there is a way to select all users and apply the same libraries to them.

Take a look at **v5.4.1-beta** on the [MUMC_dev](https://github.com/terrelsa13/MUMC/tree/MUMC_dev) branch. The next time you are creating/editing users and libraries in the config, give it a shot and let me know if the updates make your life a little easier when it comes to MUMC user management.

When creating/editing the config there will be a new question asking how you would like to build the user libraries. You will want to choose ```2```. Which will only ask to select libraries and apply those libraries to all users that have access in the GUI to the selected libraries/folders.

```
Decide how to select users and/or libraries.
0 - Select users and libraries.
    Select specific users and the specific libraries to be blacklisted for each user.
1 - Select users only.
    Selected users will have all libraries blacklisted according to their access policy.
2 - Select libraries only.
    Selected libraries will be blacklisted for all users according to their access policy.
Enter number (default 0 - Select users and libraries):
```
