### ISSUE TITLE
Wiki and github links

### ISSUE THREAD

**Issue by keppo070** [terrelsa13/media_cleaner#91]
In the wiki it says ``` git clone https://github.com/terrelsa13/MUMC.git ``` but this resolves to MUMC v4 but textual it seems the wiki is related to v5

in https://github.com/terrelsa13/MUMC/tree/MUMC-Beta it says ``` [MUMC_Latest](https://github.com/terrelsa13/MUMC/tree/MUMC-Latest) - MUMC_v5 is the current and latest branch ``` but latest resolves to v4

**Comment by terrelsa13** [comment]
You are correct AND this is correct. It is wrong on purpose.

v5 is not the current and latest branch. It is only accessible via the beta branch. But as I have been creating the wiki pages I am creating them as if v5 is the latest. That way I don't need to go back and change links again.

At some point v4 will move to a ```MUMC_v4``` branch and v5 will become the ```MUMC-Latest```.

**Comment by terrelsa13** [comment]
I added a note to the top of the v5 README saying some links broken until v5 is moved to the latest branch.
