### ISSUE TITLE
[Features] Research These Possible Feature Adds

### ISSUE THREAD

**Issue by terrelsa13** [terrelsa13/media_cleaner#94]
1. ~~Delete only when disk space is below a certain amount.~~ Not able to find API information related to disk/partition size. The only option would be to go the convoluted direction of querying the user to somehow relate media directories on the same partition to each other, then specify the desired max size for each partition. Finally the script would have to query EVERY SINGLE media item in the related directories, add up the size of each media item, and then compare that to the user specified max size. This feature is not feasible.
    1. ~~Do Emby/Jellyfin offer anything in their APIs to infer the disk size and/or remaining disk space?~~
    2. ~~How would this be handled if libraries span multiple disk partitions?~~
    3. ~~How to specify when disk space is at or below the threshold?~~
        1. ~~By bytes of disk space remaining?~~
        2. ~~By percentage of disk space remaining?~~
        4. ~~By maximum percentage of used disk space?~~
5. Delete media_items with certain properties (e.g. 1080p)
    1. This can already be manually achieved using blacktags; but tags have to be manually added.
    2. Is this a value added feature?
6. Delete media_items with respect to certain byte size (e.g. >= 10GB)
    1. This can already be manually achieved using blacktags; but tags have to be manually added
    2. Is this a value added feature?
9. ~~Update advanced filter statement control to be more explicit~~
    1. ~~https://github.com/terrelsa13/MUMC/wiki/mumc_configyaml-advanced_settings-filter_statements-media_type-query_filter-conditional_behavior~~

**Comment by keppo070** [comment]
It would like to see a basic GUI to create a mumc_config.yaml file. Could be as simple as a webpage. preferable with a pane which shows the result.

**Comment by terrelsa13** [comment]
@keppo070 I have no plans or time to make a GUI for MUMC. However, this is an open-source project. If you or someone else would like to contribute by making a GUI, that is more than acceptable.
